var str='likhitha';
const str1=str.toLowerCase();
console.log(str1);
const str11=str.toUpperCase();
console.log(str2);
const str12=str.charAt(2);
console.log(str12);
const index=str.indexOf('a');
console.log(index);
const con=str.concat('t');
console.log(con);
const include=str.includes('li');
console.log(include);
const replace = str.replace('li','le');
console.log(replace);
const split = str.split('i');
console.log(split);
const sub=str.substr(2,4)
console.log(sub);
const search=str.search('li',2);
console.log(search);
const trim=str.trim();
console.log(trim);
console.log('==========2=========');
var str2='thondamalalikhitha';
const str21=str2.toLowerCase();
console.log(str21);
const str22=str2.toUpperCase();
console.log(str22);
const str23=str2.charAt(2);
console.log(str23);
const index1=str2.indexOf('a');
console.log(index1);
const con1=str2.concat('t');
console.log(con1);
const include1=str2.includes('li');
console.log(include1);
const replace1 = str2.replace('li','le');
console.log(replace1);
const split1 = str2.split('i');
console.log(split1);
const sub1=str2.substr(2,4)
console.log(sub1);
const search1=str2.search('li',2);
console.log(search1);
const trim1=str2.trim();
console.log(trim1);
console.log('==========3=========')
var str3='hello my dear friend';
const str31=str3.toLowerCase();
console.log(str31);
const str32=str3.toUpperCase();
console.log(str32);
const str33=str3.charAt(4);
console.log(str33);
const index2=str3.indexOf('u');
console.log(index2);
const con2=str3.concat('s');
console.log(con2);
const include2=str3.includes('friend');
console.log(include2);
const replace2 = str3.replace('he','hi');
console.log(replace2);
const split2 = str3.split('o');
console.log(split2);
const sub2=str3.substr(1,5)
console.log(sub2);
const search2=str3.search('end',2);
console.log(search2);
const trim2=str3.trim();
console.log(trim2);
console.log('========4==========');
var str4="thondamalalikhitha@gmail.com"
const str41=str4.toLowerCase();
console.log(str41);
const str42=str4.toUpperCase();
console.log(str42);
const str43=str4.charAt(5);
console.log(str43);
const index3=str4.indexOf('@');
console.log(index3);
const con3=str4.concat('17');
console.log(con3);
const include3=str4.includes('@gmail');
console.log(include3);
const replace3 = str4.replace('ho','hi');
console.log(replace3);
const split3 = str4.split('n');
console.log(split3);
const sub3=str4.substr(3,6)
console.log(sub3);
const search3=str4.search('nda',2);
console.log(search3);
const trim3=str4.trim();
console.log(trim3);
console.log('=========5========');
var str5 = 'saikiran@nani'
const str51=str5.toLowerCase();
console.log(str51);
const str52=str5.toUpperCase();
console.log(str52);
const str53=str5.charAt(4);
console.log(str53);
const index4=str5.indexOf('n');
console.log(index4);
const con4=str5.concat('s');
console.log(con4);
const include4=str5.includes('nan');
console.log(include4);
const replace4 = str5.replace('ai','aa');
console.log(replace4);
const split4 = str5.split('k');
console.log(split4);
const sub4=str5.substr(1,5)
console.log(sub4);
const search4=str5.search('kiran',2);
console.log(search4);
const trim4=str5.trim();
console.log(trim4);


